spring:
  config.activate.on-profile: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:h2:../hsqldb/testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: false
        format_sql: false
