server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:log4jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.default_batch_fetch_size: 1000

logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
