server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.default_batch_fetch_size: 1000

logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
