spring:
  profiles:
    group:
      local: local,mysql,security,property-local
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  profiles:
    group:
      dev: dev,property-dev
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  profiles:
    group:
      prod: prod,property-prod
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  profiles:
    active: local
